### ISSUE TITLE
How to visualize the result of "ndn-v2v-simple.cpp"

### ISSUE THREAD

**Issue by Zakaria55** [4th-ndn-hackathon/ndnSIM-Mobile-Simulation-Package#5]
Hi every one,
I tried to run this command to see the result of "ndn-v2v-simple.cpp" and I obtained this :

zakaria@ubuntu:~/ndnSIM/ns-3$ **./waf --run=ndn-v2v-simple --vis**
Waf: Entering directory `/home/zakaria/ndnSIM/ns-3/build'
Waf: Leaving directory `/home/zakaria/ndnSIM/ns-3/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (2.816s)
V2VTest Simulator

How can I see what's happening?
Thanks in advance.

**Comment by TronYY** [comment]
Just add these two lines at the start of the main() function


 CommandLine cmd;
 cmd.Parse(argc, argv);

**Comment by Zakaria55** [comment]
> Just add these two lines at the start of the main() function
> 
> CommandLine cmd;
> cmd.Parse(argc, argv);

Hi TronYY,

Thanks for your reply. I've added the two lines but still can't see what's happening:

int
main(int argc, char* argv[])
{
  CommandLine cmd;
  cmd.Parse(argc, argv);
  return ns3::main(argc, argv);
}

**Comment by TronYY** [comment]
zakaria@ubuntu:~/ndnSIM/ns-3$ ./waf --run=ndn-v2v-simple --vis

Do you still run as this?  I can visualize the scenario after adding those two lines.

**Comment by Zakaria55** [comment]
> zakaria@ubuntu:~/ndnSIM/ns-3$ ./waf --run=ndn-v2v-simple --vis
> 
> Do you still run as this? I can visualize the scenario after adding those two lines.

Yes, it's the same command.
